### ISSUE TITLE
adding entries to NXxpcs.nxdl.xml

### ISSUE THREAD

**Issue by JulReinhardt** [lightsources/BES-XPCS-Pilot#33]
@prjemian can we add these entries to the definition file?

/entry/XPCS/instrument/mask/mask
/entry/XPCS/instrument/mask/dqmap
/entry/XPCS/instrument/mask/dqlist
/entry/XPCS/instrument/mask/dphilist
/entry/XPCS/instrument/mask/sqmap

They are already in the NX converter (NXxpcs class and the loaders).

**Comment by prjemian** [comment]
They are used by `nx_creator_xpcs` here: https://github.com/lightsources/BES-XPCS-Pilot/blob/fdfc441a0608b580e4e6ef3e2a94dedcb3829102/creator/nx_creator_xpcs.py#L173-L178

Per the NXxpcs file, I'll also change `mask` to the plural `masks`.  https://github.com/lightsources/BES-XPCS-Pilot/blob/8fce7ef8bce2d7f7ddcb69061e13fa51511a77ed/NeXus/NXxpcs.nxdl.xml#L255

**Comment by prjemian** [comment]
Each field should have some descriptive documentation.  Where can I find that?  The spreadsheet?

**Comment by prjemian** [comment]
Note that `dqmap` should not have any units since it is an index array with integer values that are indices of `dqlist`.

**Comment by prjemian** [comment]
Should these fields actually have arbitrary units?  We have an expectation for each:

field | expected units | NeXus unit type
:--- | :--- | :---
`dqlist` | `1/Angstrom` | `NX_PER_LENGTH`
`dphilist` | `degrees` | `NX_ANGLE`
`sqlist` | `1/Angstrom` | `NX_PER_LENGTH`

Also, since `sqlist` indexes (points to) values in `sqmap`, we should add that field to the support.
