### ISSUE TITLE
frame_sum and frame_average

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#44]
- need both because people are doing one or both
- units:
- [x] NX: @prjemian put in NX issue for this - need to resolve first. Pete decides.
- [x] pint: has counts and counts per second

- required: optional for both
- 
- [x] do we need a label (unit label attribute) -- this will be `NX_COUNT`

**Comment by prjemian** [comment]
follow: https://github.com/nexusformat/definitions/issues/932

**Comment by prjemian** [comment]
[NeXus intends](https://github.com/nexusformat/definitions/issues/932#issuecomment-869719661) to add `NX_COUNT` (singular) to the list of unit types.

**Comment by JulReinhardt** [comment]
So will we not simply use "counts" as unit here?

**Comment by prjemian** [comment]
We can continue to use `units="counts"` here as I believe NeXus will approve the addition an an `NX_COUNTS` type of units.  The `pint` package recognizes `"counts"` as a kind of units.

The NeXus issue (https://github.com/nexusformat/definitions/issues/932) is scheduled for consideration at the next NIAC meeting (Sept or Oct this year).  This issue was discussed at the NeXus teleconference this week ([2021-07-28](https://www.nexusformat.org/Telco_20210728.html)).

**Comment by ambarb** [comment]
@prjemian updated us on this state of htings in the NX community.  

for our case, do we want to require a label?  
@ambarb find out what XPCS community wants (counts, counts per second) for average or sum list.

**Comment by ambarb** [comment]
units will be NXcounts and pretend that it is a standard definition in NX so once this unit label attribute is added here(to our current PR), we can move this to complete.

**Comment by prjemian** [comment]
This is part of PR#52.
