### ISSUE TITLE
add new field G2_unnormalized

### ISSUE THREAD

**Issue by prjemian** [lightsources/BES-XPCS-Pilot#46]
add new field G2_unnormalized per Andi's powerpoint

**Comment by ambarb** [comment]
https://github.com/lightsources/BES-XPCS-Pilot/issues/45

**Comment by JulReinhardt** [comment]
implemented see https://github.com/lightsources/BES-XPCS-Pilot/pull/52

**Comment by ambarb** [comment]
@prjemian maybe this is in the vein of what we discussed at the end of the call: two methods for tow-time normalization?  or is this for lower case g^(2) (t)

**Comment by prjemian** [comment]
I was thinking we'd add a field that defines the basis (zero or one) used for g2 normalization.

**Comment by ambarb** [comment]
in discussing, we have two options:

1.  if mutually exclusive, we need only one field.  however, we add an attribute to declare if ideal baseline =0 or =1.  This attribute should be required.
2. if not always mutually exclusive, then we need 2.

**Comment by ambarb** [comment]
see also #49 for plain text naming convention

**Comment by ambarb** [comment]
So we can make mutually exclusive and someone can just "re-run the calculation" and create a new file.  I think we should add an attribute to the two time called:
- `baseline_from_normalization`
- `baseline_reference`
- `baseline_nomralization_method`

The allowed value with be a constant (typically 1 or 0) depending on the methods imposed for normalization.  Since the g2_partials are extrated from the two-time, then should all be consistent and (should all be kept together as fields belonging to the same subentry.
